### ISSUE TITLE
Blender OBJ format import

### ISSUE THREAD

**Issue by sczerwinski** [GlimpseFramework/glimpse-framework#14]

**Comment by elect86** [comment]
Hi Sławomir,

May a kotlin [glm](https://github.com/elect86/glm) and [assimp](https://github.com/java-graphics/assimp) interest you?

**Comment by sczerwinski** [comment]
Hi Giuseppe,
Thanks for the links.
I prefer to use as few dependencies as possible in Glimpse Framework.
However, both your projects look pretty cool. I might look into them when I have some more time for OSS again.
